### PR TITLE
Compatibility to jQuery 1.9.1

### PR DESCRIPTION
**Pull request by msburgstaller**
Compatibility to jQuery 1.9.1 - changed deprecated functions to supported ones.

### CODE REVIEW

**Comment by maxpowel** [comment]
Thank you mate ;)

**Comment by josepaul28** [comment]
hi.! can i send or receive messages with image files across Facebook XMPP chat..? I the test, i receive a image as HTML CODE <attachment>www.facebook.com/messages/3534534.. or something like that, then, i checked the received object searching the picture url but nothing

**Comment by maxpowel** [comment]
Did you try to console.log the received message? Does the image url exist (is not blank) in the received message?
Maybe the problem is you cant hotlinking images, try to copy and paste the url in your web browser

**Comment by josepaul28** [comment]
Hi!

Yes, in the log console i received a object like this:

Object 
attributes: NamedNodeMap
0: Attr
1: Attr
2: Attr
constructor: function Object() {
length: 3
**proto**: NamedNodeMapPrototype
body: "&lt;1 attachment&gt; http://www.facebook.com/messages/?action=read&amp;tid=2f9491e4350d46d09d77f3c65a38d59e"
data: Object[1]
from: "-57294397@chat.facebook.com"
**proto**: Object

the conversation box show the message "1 attachment http://www.facebook.com/messages/?action=read&tid=2f9491e4350d46d09d77f3c65a38d59e"

but this link received is not of the image sent, is the url of the conversation on FaceBook and because this, i don't think that the problem is the hotlinking 

Excuse my bad english, I'm from Venezuela, thanks for your reply

Regards.

Paul Soto

**Comment by josepaul28** [comment]
Hi!

Yes, in the log console i received a object like this:

Object 
attributes: NamedNodeMap
0: Attr
1: Attr
2: Attr
constructor: function Object() {
length: 3
**proto**: NamedNodeMapPrototype
body: "&lt;1 attachment&gt; http://www.facebook.com/messages/?action=read&amp;tid=2f9491e4350d46d09d77f3c65a38d59e"
data: Object[1]
from: "-57294397@chat.facebook.com"
**proto**: Object

the conversation box show the message "<1 attachment> http://www.facebook.com/messages/?action=read&tid=2f9491e4350d46d09d77f3c65a38d59e"

but this link received is not of the image sent, is the url of the conversation on FaceBook and because this, i don't think that the problem is the hotlinking 

Excuse my bad english, I'm from Venezuela, thanks for your reply

Regards.

Paul Soto

**Comment by maxpowel** [comment]
If the console.log shows the right message then the problem is in the client side.
Remember that all messages al processed by jQuery wich means you need to use .find("tagname") to get contents enclosed by tags in the body.

Try to do body.find("1 attachment") or body.html()

If it doesn't work, tell me exactly the message you send

**Pull request merged**
